name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      MIX_ENV: test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: '23'
          elixir-version: '1.12.1'
      - name: Check for cached dependencies
        uses: actions/cache@v1
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
          restore-keys: |
            ${{ runner.os }}-mix-
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Setup project
        run: mix setup
      - name: Check format
        run: mix format --check-formatted
      - name: Run dialyzer
        run: mix dialyzer
      - name: Run tests
        run: mix test
