name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: nurse_test
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    env:
      MIX_ENV: test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Elixir
          uses: erlef/setup-beam@v1
          with:
            otp-version: '23'
            elixir-version: '1.12.1'
      - name: Check for cached dependencies
        uses: actions/cache@v1
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
          restore-keys: |
            ${{ runner.os }}-mix-
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Setup project
        run: mix setup
      - name: Check format
        run: mix format --check-formatted
      - name: Run tests
        run: mix test
